# Generated by Django 6.1 on 2026-09-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='employer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
