# Generated by Django 6.1 on 2026-09-14 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('program', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('university', 'University'), ('high_school', 'High School'), ('middle_school', 'Middle School')], default='university', max_length=20)),
                ('description', models.TextField()),
                ('logo', models.URLField(blank=True, null=True)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
