# Generated by Django 6.1 on 2026-09-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_skill_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
